services:
  - type: web
    name: santa-fe-results-board
    runtime: static
    staticPublishPath: public
    buildCommand: npm run build
    envVars:
      - key: RACE_HOST
        value: santafehalfmarathon.com
